services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.development.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend:
    volumes:
      - ./backend:/app # コードのリアルタイム同期化
    env_file:
      - ./backend/.env.development.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    # pdf_tmp ボリュームの権限問題を解決するために、root ユーザーでコンテナを起動します。
    user: root
    # DB準備 > DB初期化 > 権限変更 > Gunicorn実行(一般ユーザー) の順番ですべての作業を統合します。
    command: >
      sh -c "python /app/wait_for_db.py && 
             python /app/db_manage.py init &&
             chown -R appuser:appgroup /tmp/pdf &&
             chown -R appuser:appgroup /app/logs &&
             exec gunicorn --bind 0.0.0.0:5001 --reload --user appuser --group appgroup 'app:app'"
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/auth/health"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  nginx:
    # container_name: nginx-local-container
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
    # frontendとbackendがhealthyな状態になるまで待ちます。
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

  mysql:
    # container_name: mysql-local-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_local:/var/lib/mysql

  rq-worker:
    env_file:
      - ./backend/.env.development.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app # コードのリアルタイム同期化
    user: root
    command: >
      sh -c "su -s /bin/sh -c 'python -m apps.ninestarki.worker_entrypoint' appuser"
    depends_on:
      - redis
      - mysql

  # --- テスト 専用 サービス ---
  backend-test:
    user: root
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development # pytestがインストールされたdevelopmentステージを使用
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development.backend
    environment:
      - PYTHONPATH=/app
    depends_on:
      backend:
        condition: service_healthy
    # コンテナが起動された時に、何もしないように待たせるコマンド
    # 通常は何もしないで待機するが、make testコマンドで上書きされた時にのみ一時的に使用される
    command: ["tail", "-f", "/dev/null"] 
    networks:
      - app-network

networks:
  app-network:
    # ネットワーク名を明示的に指定して一貫性を保ちます。
    name: app-network

volumes:
  mysql_data_local: