/app/logs/access.log {
    daily
    rotate 60
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
    size 100M
    dateext
    dateformat -%Y-%m-%d
    olddir /app/logs/archive/access
    extension .log
    su root root
}

/app/logs/error.log {
    daily
    rotate 60
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
    size 100M
    dateext
    dateformat -%Y-%m-%d
    olddir /app/logs/archive/error
    extension .log
    su root root
}

/app/logs/app.log {
    daily
    rotate 90
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
    dateext
    dateformat -%Y-%m-%d
    olddir /app/logs/archive/app
    extension .log
    su root root
}
