# http, events 等 Nginx のグローバル設定
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ログフォーマット
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # 基本設定
    sendfile        on;
    keepalive_timeout  65;

    # CORSヘッダーの設定
    map $http_origin $cors_header {
        default "http://localhost:3000";
    }

    # レート制限の設定: IPごとに10req/sec
    limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;

    include /etc/nginx/conf.d/*.conf;
} 