-- 陽遁・隠遁 切替日マスタ

CREATE TABLE IF NOT EXISTS `pattern_switch_dates` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `date` DATE NOT NULL UNIQUE COMMENT '切替日',
  `pattern` ENUM('SP_ASC','SP_DESC') NOT NULL COMMENT '切替後パターン',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='陽遁/隠遁 切替日マスタ'; 